---
title: "Similarity of graphs in adjecent matrix"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(visNetwork)
options(digits=3)
```

## cross sort function

```{r}
cross_sort=function(m0){
  #print(m0)
  k=nrow(m0)
  m0=cbind(m0,seq(1,k))
  a=vector()
  for(i in 1:k){
    a[i]=str_c(m0[i,]) %>% paste(collapse='')
  }
  #print(a)
  a=sort(a)
  r=str_sub(a,k+1,)
  m1=str_sub(a,1,k) %>% 
    str_split('') %>%
    unlist() %>%
    matrix(k,k) 
  #print(m1)
  m1=cbind(m1,seq(1,k))
  a=vector()
  for(i in 1:k){
    a[i]=str_c(m1[i,]) %>% paste(collapse='')
  }
  #print(a)
  a=sort(a)
  c=str_sub(a,k+1,)
  m2=str_sub(a,1,k) %>% 
    str_split('') %>%
    unlist() %>%
    as.integer() %>% 
    matrix(k,k)
  #print(m2)
  
  return (list(m2,r,c))
}

```

```{r}
k=10
p=0.3
```

## cross sort andirectional graph adjecent matrix and compare them

```{r}
m=matrix(0,k,k)
for(i in 1:(k-1)){
  for(j in (i+1):k){
    m[i,j]=rbinom(1,1,p)
    m[j,i]=m[i,j]
  }
}
m
visNetwork(nodes=tibble(id=1:k),edges=mat2link(m,F))

eigen(m)$values %>% round(2)

a=cross_sort(m)
ma=a[[1]]
ra=a[[2]]
ca=a[[3]]
ma
ra
ca
m=matrix(0,k,k)
for(i in 1:(k-1)){
  for(j in (i+1):k){
    m[i,j]=rbinom(1,1,p)
    m[j,i]=m[i,j]
  }
}
m
visNetwork(nodes=tibble(id=1:k),edges=mat2link(m,F))

eigen(m)$values %>% round(2)

b=cross_sort(m)
mb=b[[1]]
rb=b[[2]]
cb=b[[3]]
mb
rb
cb

(sum(ma==mb)-k)/(k**2-k)

```


## cross sort directional graph adjecent matrix and compare them

```{r}
m=matrix(rbinom(k**2,1,p),k,k)
m
visNetwork(nodes=tibble(id=1:k),edges=mat2link(m,F))

a=cross_sort(m)
ma=a[[1]]
ra=a[[2]]
ca=a[[3]]
ma

m=matrix(rbinom(k**2,1,p),k,k)
m
visNetwork(nodes=tibble(id=1:k),edges=mat2link(m,F))

b=cross_sort(m)
mb=b[[1]]
rb=b[[2]]
cb=b[[3]]
mb

sum(ma==mb)/k**2

```
