---
title: "arrow parquet duckdb"
output: html_document
date: "Sys.Date()"
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
```{r}
library(tidyverse)
library(arrow)
library(duckdb)
library(palmerpenguins)
```
 
```{r}
# ready csv file
write_csv(penguins,'./table0.csv')
 
# make parquet from csv via Robj
csv0=read_csv('table0.csv')
write_parquet(csv0,'table0.parquet')
rm(csv0)
 
# make tibble from parquet
tb0=read_parquet('table0.parquet',as_data_frame=T)
 
class(tb0)
head(tb0)
 
# make virtual arrow table from Robj
 
atb0=arrow_table(tb0)
collect(atb0)
 
# make allow table from parquet
 
atb0=read_parquet('table0.parquet',as_data_frame = F)
 
class(atb)
head(atb) %>% collect()
 
 
# make tibble/arrow table has just selected column from parquet
 
tb0=read_parquet('table0.parquet',c(species,island,sex),as_data_frame = T)
atb0=read_parquet('table0.parquet',c(species,island,sex),as_data_frame = T)
 
```
 
 
```{r}
# make duckdb database in memory(temporary use)
db=dbConnect(duckdb(),read_only=F)
db=dbConnect(duckdb(),read_only=T)
 
# connect or make duckdb database file(persistent)
db=dbConnect(duckdb(),'./mydb.duck')
 
# make table in duckdb from csv
duckdb_read_csv(db,name='table0',files='table0.csv',header=T)
 
# make virtual table in duckdb from tibble
duckdb_register(db,'table0',tb)
 
# make actual table in duckdb from tibble
dbWriteTable(db,'table0',tb)
 
# see tables in duckdb
dbListTables(db)
 
# see columns of table in duckdb
dbListFields(db,'table0')
 
# virtual tibble from table in ducktb
vtb1=tbl(db,'table0')
 
# virtual tibble directly from csv/R-obj, can be done by tidyverse
vtb1=tbl(db,'./table0.csv')
vtb1=tbl(db,penguins)
 
# actual tibble in memory from virtual table
tb1=collect(vtb1)
 
 
# get table in duckdb as data.frame
df1=dbReadTable(db,'table0')
 
# by SQL, get table in duckdb as data.frame
df1=dbGetQuery(db,'select * from table0')
 
# by SQL, make table as data.frame directly from csv/R-obj
df1=dbGetQuery(db,'select * from "./table0.csv"')
 
 
# make table from R-obj
dbWriteTable(db,'table0',penguins)
 
 
# remove table from db, not for virtual table
dbRemoveTable(db,'table0')
 
# close db and make memory free
dbDisconnect(db,shutdown=T)
rm(db)
gc()
```
 
 
```{r}
# make in memory duckdb from tibble
duck1=to_duckdb(tb1)
 
# make arrow from in memory ducktb
atb1=to_arrow(duck1)
 
# make in memory table from tibble
mtb1=InMemoryDataset$create(tb)
 
# make arrow from in memory table
atb1=to_arrow(mtb1)
 
# make in memory duckdb from in memory table
duck1=to_duckdb(mtb1)
 
# actual tibble from in memory tibble
tb1=collect(mtb1)
tb1=collect(atb1)
 
```
 
# duckdb from sqlite3
sqlite scanner
 
 
 
 
