---
title: "GetRequest"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
library(jsonlite)
```


```{r}
GET('https://geoapi.heartrails.com/api/json?method=getPrefectures')

arg0=list(method='getPrefectures')
GET('https://geoapi.heartrails.com/api/json', query=arg0)

fromJSON('https://geoapi.heartrails.com/api/json?method=getPrefectures')
```



```{r}
GET('https://geoapi.heartrails.com/api/json?method=getCities&prefecture=北海道')

arg0=list(method='getCities',
          prefecture='北海道')
GET('https://geoapi.heartrails.com/api/json', query=arg0)

fromJSON('https://geoapi.heartrails.com/api/json?method=getCities&prefecture=北海道')
```



```{r}
GET('https://geoapi.heartrails.com/api/json?method=getTowns&prefecture=北海道&city=札幌市')

fromJSON('https://geoapi.heartrails.com/api/json?method=getTowns&prefecture=北海道&city=札幌市')
```



https://www.post.japanpost.jp/zipcode/dl/utf-zip.html
```{r}
download.file('https://www.post.japanpost.jp/zipcode/dl/utf/zip/utf_ken_all.zip','utf_ken_all.zip')
unzip('utf_ken_all.zip',list=T)
unzip('utf_ken_all.zip')
read_csv('utf_ken_all.csv')

```



```{r}
GET('https://geoapi.heartrails.com/api/json?method=searchByPostal&postal=0600001')

fromJSON('https://geoapi.heartrails.com/api/json?method=searchByPostal&postal=0600001') |> str()

```

