---
title: "web scraping"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=F}
knitr::opts_chunk$set(echo =T,warning=F,message=F)
library(rvest)

library(RSQLite)
library(imager)
```

```{r}
if(file.exists('./rblog.rds')){
  srp0=readRDS('./rblog.rds')
}else{
  srp0=tibble(title='',link='',abst='')
}

html1=read_html('https://www.r-bloggers.com/')
Sys.sleep(1)
nd11=html_nodes(html1,'.loop-title a')
str_wrap(nd11)

nd12=html_nodes(html1,'.mh-excerpt')
str_wrap(nd12)

srp1=tibble(title=html_text(nd11),
           link=html_attr(nd11,'href'),
           abst=html_text(nd12))

srp0 %>% bind_rows(srp1) %>%
  distinct(link,.keep_all=T) %>% 
  saveRDS('./rblog.rds',compress=T)
```


```{r}
if(file.exists('./nhknews.rds')){
  srp0=readRDS('./nhknews.rds')
}else{
  srp0=tibble(title='',link='',file='')
}

html2=read_html('https://www3.nhk.or.jp/news/catnew.html')
Sys.sleep(1)
nd21=html_nodes(html2,'.thumb img')
str_wrap(nd21)

srp2=tibble(title=html_attr(nd21,'alt'),
            link=str_c('https://www3.nhk.or.jp',
                          html_attr(nd21,'data-src')))
srp2$file='./nhk_img/' %+% str_sub(srp2$link,-20,-1)
download.file(srp2$link,srp2$file,mode='wb')

srp0 %>% bind_rows(srp2) %>%
  distinct(file,.keep_all=T) %>% 
  arrange(desc(file)) %>% 
  saveRDS('./nhknews.rds',compress=T)
```
